name: leaderboard
owner: hefehoo@gmail.com

module:
  leaderboard:
    listen: 127.0.0.1:9090
    database: root:123456@tcp(127.0.0.1:3306)/gotest?charset=utf8mb4&parseTime=True
    read_timeout: 10  # Second
    write_timeout: 10 # Second